---

- name:  Add key for kibana
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch 
    state: present

- name: Installing dependencies ...
  apt: name={{ item }} state=present
  with_items:
      - apt-transport-https
      - apache2-utils

- name: Add Kibana repository...
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
  ignore_errors: yes

- name: Update cache...
  apt:
    update_cache: yes

- name: Determine if a path exists and is a directory
  stat: path=/etc/kibana
  register: kibana

- name: Installing Kibana
  apt: name=kibana state=installed
  when: not kibana.stat.exists

- name: Determine if a path exists and is a directory
  stat: path=/etc/nginx
  register: nginx

- name: Installing Kibana and Nginx dependencies ...
  apt: name=nginx state=installed
  when: not nginx.stat.exists
  notify: Start kibana service

- name: Install passlib (required for writing htpasswd file)...
  apt:
    name: python-passlib
    state: present

- name: Create htpasswd file to restrict access to Kibana web interface...
  htpasswd:
    name: "{{ elk_kibana_username }}"
    password: "{{ elk_kibana_password }}"
    path: /etc/nginx/htpasswd.users
  
- name: Adding Nginx configuration file ...
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml

- name: Adding Nginx configuration file ...
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify:
    - Restart kibana service
    - Restart nginx service

