---

- name: Downloading kibana package ...
  shell: "wget https://artifacts.elastic.co/downloads/kibana/kibana-5.1.1-x86_64.rpm"


- name: installing kibana ...
  command: rpm -ivh kibana-5.1.1-x86_64.rpm
  ignore_errors: yes

- name: Adding kibana configuration file ...
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml

- name: Start service kibana
  service: name=kibana state=started enabled=yes

- name: Installing Nginx dependencies ...
  yum: name={{ item }} state=installed
  with_items:
      - epel-release
      - httpd-tools

- name: Installing Nginx dependencies ...
  yum: name=nginx state=installed

- name: Starting kibana
  service: name=kibana state=started

- name: Adding nginx configuration file ...
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Adding nginx configuration file ...
  template: src=kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf
 
- name: Install passlib (required for writing htpasswd file).
  yum:
    name: python-passlib
    state: present

- name: Create htpasswd file to restrict access to Kibana web interface.
  htpasswd:
    name: "{{ elk_kibana_username }}"
    password: "{{ elk_kibana_password }}"
    path: /etc/nginx/.kibana-user

- name: Starting Kibana service
  service: name=kibana state=started


- name: Starting Nginx server
  service: name=nginx state=started

