---
- name: checking kibana already installed...
  stat: path=/etc/kibana
  register: kibana 

- name: Downloading kibana package ...
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-5.1.1-x86_64.rpm
    dest: /root/
  when: not kibana.stat.exists

- name: Installing kibana ...
  yum:
    name: kibana-5.1.1-x86_64.rpm
    state: present
  when: not kibana.stat.exists

- name: Adding kibana configuration file ...
  template: src=kibana.yml.j2 dest=/etc/kibana/kibana.yml

- name: checking nginx already installed...
  stat: path=/etc/nginx
  register: nginx

- name: Installing Nginx dependencies ...
  yum: name={{ item }} state=present
  with_items:
      - epel-release
      - httpd-tools
      - python-passlib

- name: Installing Nginx ...
  yum: name=nginx state=present
  when: not nginx.stat.exists

- name: Adding nginx configuration file ...
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf 

- name: Adding nginx configuration file ...
  template: src=default.j2 dest=/etc/nginx/conf.d/kibana.conf

- name: Create htpasswd file to restrict access to Kibana web interface.
  htpasswd:
    name: "{{ elk_kibana_username }}"
    password: "{{ elk_kibana_password }}"
    path: /etc/nginx/htpasswd.users
  notify:
    - Restart kibana service
    - Restart nginx service
