---
# handlers file for kibana

- name: Start kibana service
  service: name=kibana state=started

- name: Restart kibana service
  service: name=kibana state=restarted


- name: Start nginx service
  service: name=nginx state=started

- name: Restart nginx service
  service: name=nginx state=restarted
